### ISSUE TITLE
Upgrades al Installer

### ISSUE THREAD

**Issue by 27joaco** [mcolombo87/OrangeInstaller#14]
Installer:

- [ ] Logueo básico o simple donde diga solo lo esencial que debe saber el cliente sobre la instalación.
Installer para empleados:
- [ ] Que se puedan instalar de a más de uno (por ejemplo quiero dejar instalando por versión de repo).
- [ ] Logueo full como está actualmente
- [ ] Opción para instalar solo "Datos de conexión" (Company.data), solo "settings" y solo "carpetas" (checkouts)
Installer cliente:
- [ ] En vez de compania le pediría un código que se lo damos nosotros y los datos de conexión a la base de Installer deberían estar bien encriptados o no estar directamente.

**Comment by 27joaco** [comment]
- [x] Traducciones según language del conf.cfg

**Comment by mcolombo87** [comment]
*Traducciones según language del conf.cfg (Check)

**Comment by mcolombo87** [comment]
Pendientes re distribuidos. Ver Milestones
