### ISSUE TITLE
Bug instalador en Linux

### ISSUE THREAD

**Issue by 27joaco** [mcolombo87/OrangeInstaller#15]
- Al parecer no está bien parseada la creación del settings y lo creo en la carpeta home con el nombre: Prueba\settings\settings.xml cuando mi conf.cfg era: DefaultPath=OpenOrange/Prueba

- Pasar los tabs del settings a 4 espacios en lo posible, no rompe nada pero es así como se generan los settings.

- Al hacer checkout de ar se pasó así el comando: svn://svn.openorange.com/country/ar cuando es country/ar.repo

**Comment by mcolombo87** [comment]
Punto 1. Se solucionó en el commit 6d5b8f1. Posiblemente se extienda una rama de la versión 0.9 para corregir ahí también (se está evaluando)
Punto 2. No tiene sentido el trabajo adicional que genera. El settings se fabrica con una librería indicando nodos e hijos el espaciado lo genera automático, de igual manera lo que importa son las aperturas y los cierres.
Punto 3. El error no es de Orange Installer, la información que está cargada en la base es incorrecta. El instalador leyó "country/ar" como el repositorio a instalar ya que así se definió. Corregir en la BD.
