### ISSUE TITLE
Carpeta de Destino con CompanyName

### ISSUE THREAD

**Issue by mcolombo87** [mcolombo87/OrangeInstaller#20]
Evaluar que la carpeta de destino siempre sea con el Nombre de la empresa. Al menos como opción.

**Comment by mcolombo87** [comment]
Es decir, por defecto siempre es "OpenOrange". Tal vez debería ser el nombre de la empresa para evitar que si tenían un cliente ya instalado se los pise y haga desastre.

**Comment by 27joaco** [comment]
Corregido
