### ISSUE TITLE
Error en Seleccion de Empresas

### ISSUE THREAD

**Issue by mcolombo87** [mcolombo87/OrangeInstaller#21]
Cuando se ejecuta mediante la interfaz de usuario, dada ciertas condiciones el programa puede equivocar la empresa y traer los módulos de instalación de otra. Para que esto suceda debe coincidir que:

-  Debe seleccionarse una Empresa cuyo nombre sea exactamente igual a otra o un parte idéntica del nombre de otra empresa.

Ejemplo, 2 empresas (miempresa, miemp), la primera tiene un id más chico que la segunda. Si se realiza una búsqueda del tipo "miem", en pantalla se enlistan ambas empresas para que se seleccione la correcta. Si se selecciona la del nombre más chico (miemp), cuando busca los módulos los busca por nombre y al existir más de un resultado toma el primero de la lista (es decir "miempresa") lo cual termina en una instalación incorrecta.

**Comment by 27joaco** [comment]
Corregido
