### ISSUE TITLE
Accesos directos (windows)

### ISSUE THREAD

**Issue by mcolombo87** [mcolombo87/OrangeInstaller#26]
En WINDOWS, permitir crear accesos directos del cliente instalado. Esto debe ser opcional.

**Comment by mcolombo87** [comment]
Esto va para la 2.0 mejor.

**Comment by 27joaco** [comment]
@mcolombo87: subido, requiere winshell. por ahora lo puse harcodeado para que siempre lo cree. revisar de hacerlo segun la opcion avanzada y agregar opcion "con consola" para que le mande al metodo si ejecutar el Open con o sin consola

**Comment by mcolombo87** [comment]
Joya! encaramos todas las opciones en la semana. Lo voy a levantar como un issue aparte. Cierro.
