### ISSUE TITLE
Cambiar Iconos

### ISSUE THREAD

**Issue by mcolombo87** [mcolombo87/OrangeInstaller#35]
En Linux hay muchas diferencias entre los iconos que maneja gnome en distintas distribuciones. Tendremos que usar nuestros propios iconos, buscarlos, descargarlos y reemplazarlos por los del sistema. (Ver si se puede hacer lo mismo con el asistente de directorios, el de seleccionar carpeta).

**Comment by 27joaco** [comment]
se agregaron los iconos al GUI. Si el empaquetado quedó bien cerrar el issue @mcolombo87

**Comment by mcolombo87** [comment]
Definitivamente solucionado.
