### ISSUE TITLE
Seguridad instalador

### ISSUE THREAD

**Issue by 27joaco** [mcolombo87/OrangeInstaller#44]
1- Codificar datos de sql de conf.cfg
2- Codificar usuario SVN y contraseña en los checkout (para que algún cliente no se quede con esos usuarios y después de que ya no esté en la empresa pueda seguir haciendo checkouts)
Facu me comentó algo que podríamos hacer con los códigos que también nos había dicho Yas:
3- Agregar una vigencia al código de compania
En principio no parecía necesario pero es bastante seguro en cuestión de que el cliente cada vez que necesite instalar le generaríamos el código con una vigencia determinada.

**Comment by mcolombo87** [comment]
Terminado. No se hizo nada con las credenciales de SVN, no me parece necesario.

1.  Se arreglo incorporó un método interno para encriptar texto y desencriptar, mediante una codificación propia.
2. Ahora todos los códigos tienen fecha de vencimiento, el instalador solo pide un código, si está vencido o no lo maneja la base de datos mediante vistas.
