### ISSUE TITLE
Problema con Procesos

### ISSUE THREAD

**Issue by mcolombo87** [mcolombo87/OrangeInstaller#47]
Cada thread al terminar su tarea se elimina el proceso. Pero si se cancela la instalación cerrando la aplicación, los threads quedan corriendo a pesar de que el proceso principal ya no lo está. Se debe enlistar los threads abiertos y si se llama a la función que finaliza la aplicación se tienen que matar cada uno de ellos.

**Comment by 27joaco** [comment]
probar con threading.enumerate y un cancel de cada thread

**Comment by 27joaco** [comment]
solucionado
