### ISSUE TITLE
Error al buscar

### ISSUE THREAD

**Issue by mcolombo87** [mcolombo87/OrangeInstaller#49]
Al buscar SMATA con el buscador de empresas (ingresando con nuestro código), lo que captura como id de empresa (companyId) es "Mutual" en lugar del ID. Esto genera que el Query para capturar los módulos no produzca resultado y el programa finalice con ERROR. No logre reproducir el error con otra empresa que no sea esa, todas traen bien el companyId. Dejo una captura con las consultas realizadas.

![image](https://user-images.githubusercontent.com/8608635/31085389-5b6daa48-a76d-11e7-856a-27c6b4210e99.png)

**Comment by mcolombo87** [comment]
Update: Lo hace con todas las empresas que en su 'name' tienen espacios.

**Comment by 27joaco** [comment]
solucionado
