### ISSUE TITLE
Error en GUI Ubuntu 14.04

### ISSUE THREAD

**Issue by mcolombo87** [mcolombo87/OrangeInstaller#51]
Error reportado por Denise Villafana.

> Hola Maxi!
>
>Te paso el error que me dio al intentar instalar:
>
>Gtk-Message: Failed to load module "overlay-scrollbar"
>Gtk-Message: Failed to load module "unity-gtk-module"
>Segmentation fault (core dumped)
>
>La versión que utilicé fue Ubuntu 14.04.5 LTS

En modo --console funciona correctamente por lo que el error está claramente al hacer el build de los componentes del GTK3

**Comment by 27joaco** [comment]
Es un error de ubuntu y hay que correrle unos comandos para la distribución. No es algo que podamos arreglar desde el instalador
